### PR TITLE
#39 fixed display name, user can now set username when signup

### PR DESCRIPTION
**Pull request by tusharraval102**

### CODE REVIEW

**Comment by tusharraval102** [comment]
This is fixing the username, so that the posts can use displayName from Firebase. Signup page is changed too.

**Review by corinne-2000 — APPROVED** [review]
This looks like it makes a lot of sense.

**Review by naregschoolwork — COMMENTED** [review]
Looks amazing! Great Job!

**Comment by Klivree** [comment]
This is free to merge 
approved

**Review by Klivree — APPROVED** [review]

**Review by shahdyousefak — APPROVED** [review]
Looks good!

**Review by anonna16 — APPROVED** [review]
Looks good and safe for merge!

**Review by QuangTran304 — COMMENTED** [review]
Great!!

**Pull request merged**
