### PR TITLE
Merging like button, comments, and follow list

### PR DESCRIPTION
**Pull request by tusharraval102**

### CODE REVIEW

**Review by QuangTran304 — COMMENTED** [review]
Everything looks good. I just need help with the Follow.js component to finalize the project.

**Comment by QuangTran304** [comment]
Conflicts solved. Ready to merge!!

**Comment by tusharraval102** [comment]
Awesome! Thanks, Quang :)

**Comment by QuangTran304** [comment]
All the test cases for acceptance tests worked.

@tusharraval102  Thank you!

**Pull request merged**
